remote: origin
target-branch: main
chart-dirs:
  - charts
  - charts/dependencies
helm-extra-args: "--timeout 600s"
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
check-version-increment: false
