{{- if .Values.azure.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: azure-cloud-manager-leader-election-role
  namespace: {{ .Values.azure.cloudManager.namespace }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
{{- end }}
