{{- if .Values.azure.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-cloud-manager-operator
  namespace: {{ .Values.azure.cloudManager.namespace }}
{{ include "rhai-on-xks-chart.imagePullSecrets" . }}
{{- end }}
