{{- if .Values.coreweave.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coreweave-cloud-manager-operator
  namespace: {{ .Values.coreweave.cloudManager.namespace }}
{{ include "rhai-on-xks-chart.imagePullSecrets" . }}
{{- end }}
