{{- if .Values.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.rhaiOperator.namespace }}/rhai-operator-webhook-cert
  name: rhai-operator-mutating-webhook-configuration
  namespace: {{ .Values.rhaiOperator.namespace }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: rhai-operator-webhook-service
        namespace: {{ .Values.rhaiOperator.namespace }}
        path: /platform-connection-isvc
    failurePolicy: Fail
    name: connection-isvc.opendatahub.io
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices
    sideEffects: NoneOnDryRun
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: rhai-operator-webhook-service
        namespace: {{ .Values.rhaiOperator.namespace }}
        path: /platform-connection-llmisvc
    failurePolicy: Fail
    name: connection-llmisvc.opendatahub.io
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - llminferenceservices
    sideEffects: NoneOnDryRun
{{- end }}
