{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: rhai-operator
    app.kubernetes.io/instance: rhai-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhai-operator-webhook-service
    app.kubernetes.io/part-of: rhai-operator
  name: rhai-operator-webhook-service
  namespace: {{ .Values.rhaiOperator.namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    name: rhai-operator
{{- end }}
