# Enable/disable all resource creation
enabled: true

# Install CRDs or not using the chart
installCRDs: true

# Common labels applied to all resources
labels: {}

# RHAI Operator configuration
rhaiOperator:
  # Operator namespace
  namespace: redhat-ods-operator
  applicationsNamespace: redhat-ods-applications
  # Manager container image
  image: quay.io/opendatahub/opendatahub-operator:latest # image is updated during Helm chart build by konflux
  # Image pull policy
  imagePullPolicy: Always
  # Related images env vars (RELATED_IMAGE_*)
  relatedImages: []
  # Example:
  # relatedImages:
  #   - name: RELATED_IMAGE_ODH_KSERVE_CONTROLLER_IMAGE
  #     value: quay.io/opendatahub/kserve-controller:latest

# Components configuration
components:
  kserve:
    # Create Kserve CR via post-install hook
    enabled: true
    spec: {}

# Azure cloud configuration
azure:
  enabled: false
  cloudManager:
    # Cloud Manager operator namespace
    namespace: rhai-cloudmanager-system
    # Cloud Manager container image
    image: quay.io/opendatahub/opendatahub-operator:latest
    # Image pull policy
    imagePullPolicy: Always
  kubernetesEngine:
    # Create AzureKubernetesEngine CR via post-install hook
    enabled: true
    spec:
      dependencies:
        certManager:
          configuration: {}
          managementPolicy: Managed
        gatewayAPI:
          configuration: {}
          managementPolicy: Managed
        lws:
          configuration: {}
          managementPolicy: Managed
        sailOperator:
          configuration: {}
          managementPolicy: Managed

# CoreWeave cloud configuration
coreweave:
  enabled: false
  cloudManager:
    # Cloud Manager operator namespace
    namespace: rhai-cloudmanager-system
    # Cloud Manager container image
    image: quay.io/opendatahub/opendatahub-operator:latest
    # Image pull policy
    imagePullPolicy: Always
  kubernetesEngine:
    # Create CoreWeaveKubernetesEngine CR via post-install hook
    enabled: true
    spec:
      dependencies:
        certManager:
          configuration: {}
          managementPolicy: Managed
        gatewayAPI:
          configuration: {}
          managementPolicy: Managed
        lws:
          configuration: {}
          managementPolicy: Managed
        sailOperator:
          configuration: {}
          managementPolicy: Managed

# Pull secret for private registries
# Use --set-file imagePullSecret.dockerConfigJson=path/to/auth.json
imagePullSecret:
  # Name of the pull secret to create in target namespaces. This name MUST not be changed
  # as it is referred also in other installed dependencies and not yet configurable.
  name: rhaii-pull-secret
  # Docker config JSON content (populated via --set-file)
  dockerConfigJson: ""
  # Namespaces created by dependency operators where pull secrets should be injected
  dependencyNamespaces:
    - cert-manager-operator
    - cert-manager
    - openshift-lws-operator
    - istio-system
