{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: rhai-operator
  name: rhai-operator
  namespace: {{ .Values.rhaiOperator.namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      name: rhai-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: rhai-operator
      labels:
        name: rhai-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - rhai-operator
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=0.0.0.0:8080
            - --leader-elect
          command:
            - /manager
          env:
            - name: DISABLE_DSC_CONFIG
              value: "true"
            - name: RHAI_DISABLE_DSC_RESOURCE
              value: "true"
            - name: RHAI_DISABLE_DSCI_RESOURCE
              value: "true"
            - name: RHAI_DISABLE_DASHBOARD_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_DATASCIENCEPIPELINES_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_FEASTOPERATOR_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_KUEUE_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_LLAMASTACKOPERATOR_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_MLFLOWOPERATOR_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_MODELCONTROLLER_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_MODELREGISTRY_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_MODELSASSERVICE_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_RAY_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_SPARKOPERATOR_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_TRAINER_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_TRAININGOPERATOR_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_TRUSTYAI_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_WORKBENCHES_COMPONENT
              value: "true"
            - name: RHAI_DISABLE_AUTH_SERVICE
              value: "true"
            - name: RHAI_DISABLE_CERTCONFIGMAPGENERATOR_SERVICE
              value: "true"
            - name: RHAI_DISABLE_GATEWAY_SERVICE
              value: "true"
            - name: RHAI_DISABLE_MONITORING_SERVICE
              value: "true"
            - name: RHAI_DISABLE_SETUPCONTROLLER_SERVICE
              value: "true"
            - name: RHAI_APPLICATIONS_NAMESPACE
              value: {{ .Values.rhaiOperator.applicationsNamespace | quote }}
            - name: ODH_PLATFORM_TYPE
              value: XKS
            - name: OPERATOR_NAME
              value: rhai-operator
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEFAULT_MANIFESTS_PATH
              value: /opt/manifests
            {{- range $item := .Values.rhaiOperator.relatedImages }}
            - name: {{ $item.name | quote }}
              value: {{ $item.value | quote }}
            {{- end }}
          image: {{ .Values.rhaiOperator.image }}
          imagePullPolicy: {{ .Values.rhaiOperator.imagePullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: rhai-operator
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: rhai-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: redhat-ods-operator-controller-webhook-cert
{{- end }}
