{{- if and .Values.enabled (include "rhai-on-xks-chart.imagePullSecretEnabled" .) }}
{{- $namespaces := list .Values.rhaiOperator.namespace .Values.rhaiOperator.applicationsNamespace .Release.Namespace }}
{{- if .Values.azure.enabled }}
{{- $namespaces = append $namespaces .Values.azure.cloudManager.namespace }}
{{- end }}
{{- if .Values.coreweave.enabled }}
{{- $namespaces = append $namespaces .Values.coreweave.cloudManager.namespace }}
{{- end }}
{{- $dependencyNamespaces := .Values.imagePullSecret.dependencyNamespaces | default list }}
{{- $allNamespaces := concat $namespaces $dependencyNamespaces | uniq }}
{{- range $i, $ns := $dependencyNamespaces }}
{{- if $i }}
---
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
{{- end }}
{{- range $ns := $allNamespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rhai-on-xks-chart.imagePullSecretName" $ }}
  namespace: {{ $ns }}
  labels:
    {{- include "rhai-on-xks-chart.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $.Values.imagePullSecret.dockerConfigJson | b64enc }}
{{- end }}
{{- end }}
{{- if and .Values.enabled (include "rhai-on-xks-chart.imagePullSecretEnabled" .) }}
---
# TODO: This is a temporary solution to inject the pull secret into the llmisvc-controller-manager service account.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llmisvc-controller-manager
  namespace: {{ .Values.rhaiOperator.applicationsNamespace }}
imagePullSecrets:
  - name: {{ include "rhai-on-xks-chart.imagePullSecretName" . }}
{{- end }}
