apiVersion: v2
name: rhai-on-openshift-chart
description: A Helm chart for installing ODH/RHOAI dependencies and component configurations
type: application
version: 3.4.0-ea.2
appVersion: "3.4.0-ea.2"
keywords:
  - openshift
  - rhoai
  - odh
  - ai
  - rhaii
  - rhai
