---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: cluster-validation-ocp420-pr{{ pull_request_number }}-{{ revision }}
  labels:
    appstudio.openshift.io/application: odh-gitops
    appstudio.openshift.io/component: cluster-validation-ocp-420
    pipelines.appstudio.openshift.io/type: test
  annotations:
    # Disabled until OCP 4.20 support is confirmed
    # pipelinesascode.tekton.dev/on-event: "[pull_request]"
    # pipelinesascode.tekton.dev/on-target-branch: "[main]"
    # pipelinesascode.tekton.dev/on-comment: "^/validate-dependencies"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "{{repo_url}}"
      - name: revision
        value: "{{revision}}"
      - name: pathInRepo
        value: .tekton/pipelines/cluster-validation-pipeline.yaml
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: ocp-version
      value: "4.20.0"
  taskRunTemplate:
    serviceAccountName: build-pipeline-cluster-validation-ocp-420
