{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhai-operator-controller-manager
  namespace: {{ .Values.rhaiOperator.namespace }}
{{ include "rhaii-helm-chart.imagePullSecrets" . }}
{{- end }}
